const PRODUCTOS_DATA = [
  {
    "id": 1,
    "nombre": "Taco Relleno Regaliz 1 kg Fini",
    "cat": "regaliz",
    "cat_label": "Regaliz",
    "art": "licorice",
    "slug": "taco-relleno-regaliz-1-kg-fini",
    "img": "images/productos/taco-relleno-regaliz-1-kg-fini.jpg",
    "img_zoom": "https://www.lekkerlandstore.com/131452-large_default/taco-relleno-regaliz-1-kg-fini.jpg",
    "price": 10.69,
    "precio_proveedor": 4.98,
    "precio_comp": 11.55,
    "meta": "¿Eres de los que no pueden parar de comer regaliz? Estos tacos cuadrados de Fini te van a enganchar: exterior negro e intenso con un relleno dulce que explota en la boca.",
    "desc_short": "¿Eres de los que no pueden parar de comer regaliz? Estos tacos cuadrados de Fini te van a enganchar: exterior negro e intenso con un relleno dulce que explota en la boca.",
    "descripcion": "Los tacos de regaliz rellenos de Fini son el sueño de cualquier fan del regaliz de verdad. Pequeñitos, compactos y con ese sabor inconfundible a regaliz negro... pero con una sorpresa: por dentro son dulces y suaves. El contraste es adictivo. Cada mordisco es una mezcla perfecta de intensidad y dulzura. Son imposibles de comer de uno en uno — te lo avisamos. Perfectos para picar solos, compartir con los amigos o rescatar cuando necesitas ese capricho de regaliz que nadie más entiende. Bolsa de 1 kg para que no te quedes sin stock demasiado pronto. Contienen gluten.",
    "descripcion_html": "<div>\n<p>Los tacos de regaliz rellenos de Fini son el sueño de cualquier fan del regaliz de verdad. Pequeñitos, compactos y con ese sabor inconfundible a regaliz negro... pero con una sorpresa: por dentro son dulces y suaves. El contraste es adictivo.</p>\n<p>Cada mordisco es una mezcla perfecta de intensidad y dulzura. Son imposibles de comer de uno en uno — te lo avisamos. Perfectos para picar solos, compartir con los amigos o rescatar cuando necesitas ese capricho de regaliz que nadie más entiende.</p>\n<p>Bolsa de 1 kg para que no te quedes sin stock demasiado pronto. Contienen gluten.</p>\n</div>",
    "referencia": "7757",
    "marca": "Fini",
    "features": [],
    "url_proveedor": "https://www.lekkerlandstore.com/regalices/661-taco-relleno-regaliz-1-kg-fini.html",
    "en_stock": true
  },
  {
    "id": 2,
    "nombre": "Ranas gigantes brillo 1 kg Fini",
    "cat": "gominolas",
    "cat_label": "Gominolas",
    "art": "bear",
    "slug": "ranas-gigantes-brillo-1-kg-fini",
    "img": "images/productos/ranas-gigantes-brillo-1-kg-fini.jpg",
    "img_zoom": "https://www.lekkerlandstore.com/140742-large_default/ranas-gigantes-brillo-1kg-fini.jpg",
    "price": 6.59,
    "precio_proveedor": 3.56,
    "precio_comp": 7.1,
    "meta": "Ranas enormes, brillantes y afrutadas que van a desaparecer del bol antes de que te des cuenta. La gominola clásica de Fini en su versión más grande y vistosa.",
    "desc_short": "Ranas enormes, brillantes y afrutadas que van a desaparecer del bol antes de que te des cuenta. La gominola clásica de Fini en su versión más grande y vistosa.",
    "descripcion": "Las Ranas Gigantes Brillo de Fini tienen todo lo que buscas en una gominola: tamaño generoso, color intenso, textura blanda que se deshace sola y un sabor afrutado que alegra el día. Su acabado brillante las hace irresistibles — tanto para comérselas como para presumir de ellas en cualquier mesa dulce. Son el clásico de los clásicos. Las reconoces, las quieres, y sabes perfectamente que cuando abres la bolsa no vas a poder parar. Ideales para compartir (o no compartir, eso ya es cosa tuya). Bolsa de 1 kg. Sin gluten.",
    "descripcion_html": "<div>\n<p>Las Ranas Gigantes Brillo de Fini tienen todo lo que buscas en una gominola: tamaño generoso, color intenso, textura blanda que se deshace sola y un sabor afrutado que alegra el día. Su acabado brillante las hace irresistibles — tanto para comérselas como para presumir de ellas en cualquier mesa dulce.</p>\n<p>Son el clásico de los clásicos. Las reconoces, las quieres, y sabes perfectamente que cuando abres la bolsa no vas a poder parar. Ideales para compartir (o no compartir, eso ya es cosa tuya).</p>\n<p>Bolsa de 1 kg. Sin gluten.</p>\n</div>",
    "referencia": "2189",
    "marca": "Fini",
    "features": [],
    "url_proveedor": "https://www.lekkerlandstore.com/gominolas/3843-ranas-gigantes-brillo-1kg-fini.html",
    "en_stock": true
  },
  {
    "id": 3,
    "nombre": "Crunchy Asteroides Surtidos 1 kg Burmar",
    "cat": "gominolas",
    "cat_label": "Gominolas",
    "art": "bear",
    "slug": "crunchy-asteroides-surtidos-1-kg-burmar",
    "img": "images/productos/crunchy-asteroides-surtidos-1-kg-burmar.jpg",
    "img_zoom": "https://www.lekkerlandstore.com/140426-large_default/crunchy-asteroides-surtidos-1-kg-burmar.jpg",
    "price": 10.39,
    "precio_proveedor": 6.34,
    "precio_comp": 11.2,
    "meta": "Bolitas crujientes con toque ácido en 8 sabores: naranja, cereza, limón, melón, fresa, cola, tropical y disco. ¡Una pequeña explosión en cada bocado!",
    "desc_short": "Bolitas crujientes con toque ácido en 8 sabores: naranja, cereza, limón, melón, fresa, cola, tropical y disco. ¡Una pequeña explosión en cada bocado!",
    "descripcion": "Los Asteroides de Burmar son esas chuches que pruebas una y no puedes parar. Tienen forma de asteroide, son crujientes por fuera, y en cuanto las muerdes sueltan un toque ácido que te hace cerrar los ojos de placer. Disponibles en 8 sabores distintos — en cada puñado te toca uno diferente, así que el juego está asegurado. Perfectas para los que disfrutan de las chuches con mordida. Ese crujido seguido de la explosión ácida-afrutada es sencillamente adictivo. Halal, sin gluten y sin lactosa, así que son para todos. Bolsa de 1 kg para las sesiones más épicas de sofá y película.",
    "descripcion_html": "<div>\n<p>Los Asteroides de Burmar son esas chuches que pruebas una y no puedes parar. Tienen forma de asteroide, son crujientes por fuera, y en cuanto las muerdes sueltan un toque ácido que te hace cerrar los ojos de placer. Disponibles en 8 sabores distintos — en cada puñado te toca uno diferente, así que el juego está asegurado.</p>\n<p>Perfectas para los que disfrutan de las chuches con mordida. Ese crujido seguido de la explosión ácida-afrutada es sencillamente adictivo. Halal, sin gluten y sin lactosa, así que son para todos.</p>\n<p>Bolsa de 1 kg para las sesiones más épicas de sofá y película.</p>\n</div>",
    "referencia": "10114",
    "marca": "Burmar",
    "features": [],
    "url_proveedor": "https://www.lekkerlandstore.com/gominolas/3699-crunchy-asteroides-surtidos-1-kg-burmar.html",
    "en_stock": true
  },
  {
    "id": 4,
    "nombre": "Piruletas Corazon 110 ud Cerdan",
    "cat": "caramelos",
    "cat_label": "Caramelos",
    "art": "wrapped",
    "slug": "piruletas-corazon-110-ud-cerdan",
    "img": "images/productos/piruletas-corazon-110-ud-cerdan.jpg",
    "img_zoom": "https://www.lekkerlandstore.com/140708-large_default/piruletas-corazon-110-ud-cerdan.jpg",
    "price": 10.09,
    "precio_proveedor": 6.34,
    "precio_comp": 10.95,
    "meta": "Una piruleta con forma de corazón y sabor a cereza que lo dice todo sin palabras. Clásica, deliciosa y perfecta para regalar o simplemente darte el gusto.",
    "desc_short": "Una piruleta con forma de corazón y sabor a cereza que lo dice todo sin palabras. Clásica, deliciosa y perfecta para regalar o simplemente darte el gusto.",
    "descripcion": "Las piruletas corazón de Cerdán llevan años siendo las protagonistas silenciosas de todas las celebraciones. Son rojas, tienen forma de corazón, saben a cereza y están envueltas una a una — no hay nadie que pueda resistírseles. Tan perfectas para una bolsa de cumpleaños como para una boda, o simplemente para sacarte el capricho un martes por la tarde. Ese sabor a cereza, dulce y directo, nunca falla. Pack de 110 unidades, cada una envuelta individualmente. Sin gluten.",
    "descripcion_html": "<div>\n<p>Las piruletas corazón de Cerdán llevan años siendo las protagonistas silenciosas de todas las celebraciones. Son rojas, tienen forma de corazón, saben a cereza y están envueltas una a una — no hay nadie que pueda resistírseles.</p>\n<p>Tan perfectas para una bolsa de cumpleaños como para una boda, o simplemente para sacarte el capricho un martes por la tarde. Ese sabor a cereza, dulce y directo, nunca falla.</p>\n<p>Pack de 110 unidades, cada una envuelta individualmente. Sin gluten.</p>\n</div>",
    "referencia": "2515",
    "marca": "Cerdán",
    "features": [],
    "url_proveedor": "https://www.lekkerlandstore.com/piruletas/3842-piruletas-corazon-110-ud-cerdan.html",
    "en_stock": true
  },
  {
    "id": 5,
    "nombre": "Smint Tabs Menta 12 ud",
    "cat": "caramelos",
    "cat_label": "Caramelos",
    "art": "wrapped",
    "slug": "smint-tabs-menta-12-ud",
    "img": "images/productos/smint-tabs-menta-12-ud.jpg",
    "img_zoom": "https://www.lekkerlandstore.com/135826-large_default/smint-tabs-menta-12-ud.jpg",
    "price": 23.69,
    "precio_proveedor": 15.01,
    "precio_comp": 25.5,
    "meta": "El clásico que nunca falla para el aliento fresco. Un golpe de menta intenso en formato mini que cabe en cualquier bolsillo.",
    "desc_short": "El clásico que nunca falla para el aliento fresco. Un golpe de menta intenso en formato mini que cabe en cualquier bolsillo.",
    "descripcion": "Smint Tabs Menta es ese producto que todo el mundo conoce y que siempre hace falta. Pequeño, discreto y con un chute de menta que actúa al instante. Perfecto para después de comer, antes de una conversación importante o simplemente porque te apetece ese frescor mentolado. Te lo metes en la boca, se disuelve solo y deja ese rastro fresco que dura más de lo que esperas. Sin azúcar, sin complicaciones. Solo frescura pura. Pack de 12 cajitas. Sin gluten.",
    "descripcion_html": "<div>\n<p>Smint Tabs Menta es ese producto que todo el mundo conoce y que siempre hace falta. Pequeño, discreto y con un chute de menta que actúa al instante. Perfecto para después de comer, antes de una conversación importante o simplemente porque te apetece ese frescor mentolado.</p>\n<p>Te lo metes en la boca, se disuelve solo y deja ese rastro fresco que dura más de lo que esperas. Sin azúcar, sin complicaciones. Solo frescura pura.</p>\n<p>Pack de 12 cajitas. Sin gluten.</p>\n</div>",
    "referencia": "1670",
    "marca": "Smint",
    "features": [],
    "url_proveedor": "https://www.lekkerlandstore.com/caramelos/3219-smint-tabs-menta-12-ud.html",
    "en_stock": true
  },
  {
    "id": 6,
    "nombre": "Cereza envuelta gragea 80 g (12 ud) Fini",
    "cat": "gominolas",
    "cat_label": "Gominolas",
    "art": "bear",
    "slug": "cereza-envuelta-gragea-80-g-12-ud-fini",
    "img": "images/productos/cereza-envuelta-gragea-80-g-12-ud-fini.jpg",
    "img_zoom": "https://www.lekkerlandstore.com/129815-large_default/cereza-envuelta-gragea-80-g-12-ud-fini.jpg",
    "price": 11.19,
    "precio_proveedor": 7.26,
    "precio_comp": 12.05,
    "meta": "Por fuera, un crujido azucarado. Por dentro, suavidad pura a cereza. El caramelo de Fini que siempre pides repetir.",
    "desc_short": "Por fuera, un crujido azucarado. Por dentro, suavidad pura a cereza. El caramelo de Fini que siempre pides repetir.",
    "descripcion": "La Cereza Envuelta Gragea de Fini es uno de esos caramelos que te enganchan desde el primero. La capa exterior azucarada cruje ligeramente y luego aparece el interior suave, dulce y con ese sabor a cereza que te lleva directo a la infancia. Una combinación sencilla pero perfecta. Caben en cualquier bolsillo, se disfrutan en cualquier momento y son de esas chuches que pides \"solo una más\" hasta que la bolsa está vacía. Fini sabe bien cómo hacer las cosas. Bolsa de 80 g, presentación de 12 unidades. Sin gluten.",
    "descripcion_html": "<div>\n<p>La Cereza Envuelta Gragea de Fini es uno de esos caramelos que te enganchan desde el primero. La capa exterior azucarada cruje ligeramente y luego aparece el interior suave, dulce y con ese sabor a cereza que te lleva directo a la infancia. Una combinación sencilla pero perfecta.</p>\n<p>Caben en cualquier bolsillo, se disfrutan en cualquier momento y son de esas chuches que pides \"solo una más\" hasta que la bolsa está vacía. Fini sabe bien cómo hacer las cosas.</p>\n<p>Bolsa de 80 g, presentación de 12 unidades. Sin gluten.</p>\n</div>",
    "referencia": "8554",
    "marca": "Fini",
    "features": [],
    "url_proveedor": "https://www.lekkerlandstore.com/gominolas/1377-cereza-envuelta-gragea-80-g-12-ud-fini.html",
    "en_stock": true
  },
  {
    "id": 7,
    "nombre": "Orbit Refreshers Hierbabuena (16 ud)",
    "cat": "chicles",
    "cat_label": "Chicles",
    "art": "gum",
    "slug": "orbit-refreshers-hierbabuena-16-ud",
    "img": "images/productos/orbit-refreshers-hierbabuena-16-ud.jpg",
    "img_zoom": "https://www.lekkerlandstore.com/141670-large_default/orbit-refreshers-hierbabuena-16-ud.jpg",
    "price": 21.29,
    "precio_proveedor": 14.47,
    "precio_comp": 22.95,
    "meta": "El chicle de hierbabuena más suave y refrescante de Orbit. Para tener el aliento fresco sin la intensidad del mentol clásico.",
    "desc_short": "El chicle de hierbabuena más suave y refrescante de Orbit. Para tener el aliento fresco sin la intensidad del mentol clásico.",
    "descripcion": "Los Orbit Refreshers de Hierbabuena son para los que buscan frescor sin agresividad. Ni demasiado fuerte ni demasiado suave — el equilibrio perfecto. Tienen una textura elástica y agradable, con un interior algo más blando que hace que masticarlos sea un placer. El sabor a hierbabuena es limpio y duradero. Se queda contigo mucho después del primer mordisco, que es exactamente lo que buscas en un chicle. Perfectos para después de comer, en el coche o simplemente cuando quieres sentirte bien. Pack de 16 unidades.",
    "descripcion_html": "<div>\n<p>Los Orbit Refreshers de Hierbabuena son para los que buscan frescor sin agresividad. Ni demasiado fuerte ni demasiado suave — el equilibrio perfecto. Tienen una textura elástica y agradable, con un interior algo más blando que hace que masticarlos sea un placer.</p>\n<p>El sabor a hierbabuena es limpio y duradero. Se queda contigo mucho después del primer mordisco, que es exactamente lo que buscas en un chicle. Perfectos para después de comer, en el coche o simplemente cuando quieres sentirte bien.</p>\n<p>Pack de 16 unidades.</p>\n</div>",
    "referencia": "7929",
    "marca": "Orbit",
    "features": [],
    "url_proveedor": "https://www.lekkerlandstore.com/chicles/4288-orbit-refreshers-hierbabuena-16-ud.html",
    "en_stock": true
  },
  {
    "id": 8,
    "nombre": "Sobres Soda Unicornios Fresa Plátano (40 ud) Cerdán",
    "cat": "caramelos",
    "cat_label": "Caramelos",
    "art": "wrapped",
    "slug": "sobres-soda-unicornios-fresa-platano-40-ud-cerdan",
    "img": "images/productos/sobres-soda-unicornios-fresa-platano-40-ud-cerdan.jpg",
    "img_zoom": "https://www.lekkerlandstore.com/140685-large_default/sobres-soda-unicornios-fresa-platano-40-ud-cerdan.jpg",
    "price": 9.79,
    "precio_proveedor": 6.65,
    "precio_comp": 10.55,
    "meta": "Piruleta de fresa y plátano + polvo efervescente pica-pica = magia pura. La chuche más divertida del universo unicornio.",
    "desc_short": "Piruleta de fresa y plátano + polvo efervescente pica-pica = magia pura. La chuche más divertida del universo unicornio.",
    "descripcion": "Cada sobre de Soda Unicornios es una pequeña aventura: abres el sobre decorado con unicornios de colores, sacas la piruleta de fresa y plátano, la mojas en el polvo efervescente... y el pica-pica explota en tu boca de una forma que es imposible no reírse. La combinación de fresa y plátano es dulce, afrutada y muy rica. Y el efecto pica-pica le da ese toque que lo convierte en algo más que un caramelo — es una experiencia. Perfectas para los peques, aunque los mayores también somos adictos. Caja de 40 sobres individuales. Sin gluten, aptas para veganos.",
    "descripcion_html": "<div>\n<p>Cada sobre de Soda Unicornios es una pequeña aventura: abres el sobre decorado con unicornios de colores, sacas la piruleta de fresa y plátano, la mojas en el polvo efervescente... y el pica-pica explota en tu boca de una forma que es imposible no reírse.</p>\n<p>La combinación de fresa y plátano es dulce, afrutada y muy rica. Y el efecto pica-pica le da ese toque que lo convierte en algo más que un caramelo — es una experiencia. Perfectas para los peques, aunque los mayores también somos adictos.</p>\n<p>Caja de 40 sobres individuales. Sin gluten, aptas para veganos.</p>\n</div>",
    "referencia": "15061",
    "marca": "Cerdán",
    "features": [],
    "url_proveedor": "https://www.lekkerlandstore.com/caramelos-con-palo/3817-sobres-soda-unicornios-fresa-platano-40-ud-cerdan.html",
    "en_stock": true
  },
  {
    "id": 9,
    "nombre": "Orbit Refreshers Tropical (16 ud)",
    "cat": "chicles",
    "cat_label": "Chicles",
    "art": "gum",
    "slug": "orbit-refreshers-tropical-16-ud",
    "img": "images/productos/orbit-refreshers-tropical-16-ud.jpg",
    "img_zoom": "https://www.lekkerlandstore.com/141676-large_default/orbit-refreshers-tropical-16-ud.jpg",
    "price": 21.29,
    "precio_proveedor": 14.47,
    "precio_comp": 22.95,
    "meta": "Piña y mango con una frescura que te transporta directo a la playa. El chicle sin azúcar más tropical de Orbit.",
    "desc_short": "Piña y mango con una frescura que te transporta directo a la playa. El chicle sin azúcar más tropical de Orbit.",
    "descripcion": "Los Orbit Refreshers Tropical son para los que quieren algo más que frescor — quieren una experiencia. Cada gragea combina la intensidad del mango y la piña con esa frescura duradera que solo Orbit consigue. Suaves por fuera, explosivos por dentro. Sin azúcar, así que puedes disfrutarlos sin culpa. Y duran lo suficiente para que el sabor tropical te acompañe mucho después del primer mordisco. El chicle perfecto para los días en que necesitas un viaje mental a algún lugar soleado. Pack de 16 unidades. Sin gluten.",
    "descripcion_html": "<div>\n<p>Los Orbit Refreshers Tropical son para los que quieren algo más que frescor — quieren una experiencia. Cada gragea combina la intensidad del mango y la piña con esa frescura duradera que solo Orbit consigue. Suaves por fuera, explosivos por dentro.</p>\n<p>Sin azúcar, así que puedes disfrutarlos sin culpa. Y duran lo suficiente para que el sabor tropical te acompañe mucho después del primer mordisco. El chicle perfecto para los días en que necesitas un viaje mental a algún lugar soleado.</p>\n<p>Pack de 16 unidades. Sin gluten.</p>\n</div>",
    "referencia": "9813",
    "marca": "Orbit",
    "features": [],
    "url_proveedor": "https://www.lekkerlandstore.com/chicles/3423-orbit-refreshers-tropical-16-ud.html",
    "en_stock": true
  },
  {
    "id": 10,
    "nombre": "Mesa Dulce Rosa",
    "cat": "conos",
    "cat_label": "Conos y cestas",
    "art": "cone",
    "slug": "mesa-dulce-rosa",
    "img": "images/productos/mesa-dulce-rosa.jpg",
    "img_zoom": "https://www.lekkerlandstore.com/140943-large_default/mesa-dulce-rosa.jpg",
    "price": 55.79,
    "precio_proveedor": 37.95,
    "precio_comp": 60.0,
    "meta": "Todo lo que necesitas para montar una mesa dulce en tonos rosas: chuches variadas, sabores a fresa y un resultado que es pura ternura.",
    "desc_short": "Todo lo que necesitas para montar una mesa dulce en tonos rosas: chuches variadas, sabores a fresa y un resultado que es pura ternura.",
    "descripcion": "La Mesa Dulce Rosa está pensada para que montar una mesa de chuches sea fácil, bonita y deliciosa. Incluye una selección de golosinas en tonos rosados — suaves, masticables y con ese sabor a fresa que lo llena todo de alegría. Contiene Yaketas Minicorazón de Jake, Torcidas Fresa de Fini, Finitronc Bicolor de Fini, Bolas Rosas de Bulgari y Besos Fresa 1 kg de Fini. Todo coordinado en rosa para que el resultado sea tan bonito como rico. Ideal para comuniones, baby showers, cumpleaños o cualquier celebración que quieras llenar de color y dulzura.",
    "descripcion_html": "<div>\n<p>La Mesa Dulce Rosa está pensada para que montar una mesa de chuches sea fácil, bonita y deliciosa. Incluye una selección de golosinas en tonos rosados — suaves, masticables y con ese sabor a fresa que lo llena todo de alegría.</p>\n<p>Contiene Yaketas Minicorazón de Jake, Torcidas Fresa de Fini, Finitronc Bicolor de Fini, Bolas Rosas de Bulgari y Besos Fresa 1 kg de Fini. Todo coordinado en rosa para que el resultado sea tan bonito como rico.</p>\n<p>Ideal para comuniones, baby showers, cumpleaños o cualquier celebración que quieras llenar de color y dulzura.</p>\n</div>",
    "referencia": "15109",
    "marca": "Fini",
    "features": [],
    "url_proveedor": "https://www.lekkerlandstore.com/golosinas/3992-mesa-dulce-rosa.html",
    "en_stock": true
  },
  {
    "id": 11,
    "nombre": "Oreo doble crema 157 g (16 ud)",
    "cat": "chocolate",
    "cat_label": "Chocolate",
    "art": "choc",
    "slug": "oreo-doble-crema-157-g-16-ud",
    "img": "images/productos/oreo-doble-crema-157-g-16-ud.jpg",
    "img_zoom": "https://www.lekkerlandstore.com/135742-large_default/oreo-doble-crema-185-g-12-ud.jpg",
    "price": 30.59,
    "precio_proveedor": 20.85,
    "precio_comp": 32.95,
    "meta": "Las Oreo de siempre, pero con el doble de crema. Porque a veces lo bueno puede ser todavía mejor.",
    "desc_short": "Las Oreo de siempre, pero con el doble de crema. Porque a veces lo bueno puede ser todavía mejor.",
    "descripcion": "Las Oreo Double Creme son la respuesta a todos los que siempre dijeron que las Oreo normales no tenían suficiente relleno. Dos galletas de chocolate negro, una capa de crema de vainilla el doble de gruesa que la original. Resultado: pura felicidad. Puedes comerlas enteras, abrirlas por la mitad y lamer la crema, o mojarlas en leche — el ritual clásico funciona igual o mejor con el doble de relleno. No hay forma de equivocarse. Caja con 16 unidades.",
    "descripcion_html": "<div>\n<p>Las Oreo Double Creme son la respuesta a todos los que siempre dijeron que las Oreo normales no tenían suficiente relleno. Dos galletas de chocolate negro, una capa de crema de vainilla el doble de gruesa que la original. Resultado: pura felicidad.</p>\n<p>Puedes comerlas enteras, abrirlas por la mitad y lamer la crema, o mojarlas en leche — el ritual clásico funciona igual o mejor con el doble de relleno. No hay forma de equivocarse.</p>\n<p>Caja con 16 unidades.</p>\n</div>",
    "referencia": "1364",
    "marca": "Oreo",
    "features": [],
    "url_proveedor": "https://www.lekkerlandstore.com/galletas/3218-oreo-doble-crema-185-g-12-ud.html",
    "en_stock": true
  },
  {
    "id": 12,
    "nombre": "Panna Fragola 200 Ud Fini",
    "cat": "chicles",
    "cat_label": "Chicles",
    "art": "gum",
    "slug": "panna-fragola-200-ud-fini",
    "img": "images/productos/panna-fragola-200-ud-fini.jpg",
    "img_zoom": "https://www.lekkerlandstore.com/140736-large_default/chicle-panna-fragola-200-ud-fini.jpg",
    "price": 10.89,
    "precio_proveedor": 7.56,
    "precio_comp": 11.75,
    "meta": "Un chicle grageado de Fini con relleno líquido de fresa que explota en la boca. El chicle que convierte cada masticada en una sorpresa.",
    "desc_short": "Un chicle grageado de Fini con relleno líquido de fresa que explota en la boca. El chicle que convierte cada masticada en una sorpresa.",
    "descripcion": "El Panna Fragola de Fini tiene un secreto: por dentro esconde un relleno líquido de fresa que te explota en la boca en cuanto lo muerdes. Lo que parece un chicle grageado normal se convierte de repente en una experiencia completamente diferente. Sabor intenso a fresa, textura agradable y ese momento de sorpresa con el relleno líquido que nunca deja de ser divertido. Es el tipo de chicle que le das a alguien sin decirle lo que va a pasar — su cara no tiene precio. Caja de 200 unidades, cada una envuelta individualmente. Sin gluten.",
    "descripcion_html": "<div>\n<p>El Panna Fragola de Fini tiene un secreto: por dentro esconde un relleno líquido de fresa que te explota en la boca en cuanto lo muerdes. Lo que parece un chicle grageado normal se convierte de repente en una experiencia completamente diferente.</p>\n<p>Sabor intenso a fresa, textura agradable y ese momento de sorpresa con el relleno líquido que nunca deja de ser divertido. Es el tipo de chicle que le das a alguien sin decirle lo que va a pasar — su cara no tiene precio.</p>\n<p>Caja de 200 unidades, cada una envuelta individualmente. Sin gluten.</p>\n</div>",
    "referencia": "7819",
    "marca": "Fini",
    "features": [],
    "url_proveedor": "https://www.lekkerlandstore.com/chicles/3853-chicle-panna-fragola-200-ud-fini.html",
    "en_stock": true
  },
  {
    "id": 13,
    "nombre": "Caramelo relleno de miel 1 kg Gerio",
    "cat": "caramelos",
    "cat_label": "Caramelos",
    "art": "wrapped",
    "slug": "caramelo-relleno-de-miel-1-kg-gerio",
    "img": "images/productos/caramelo-relleno-de-miel-1-kg-gerio.jpg",
    "img_zoom": "https://www.lekkerlandstore.com/129872-large_default/caramelo-relleno-de-miel-1-kg-gerio.jpg",
    "price": 11.59,
    "precio_proveedor": 8.08,
    "precio_comp": 12.5,
    "meta": "El caramelo de toda la vida, relleno de miel. Suave, reconfortante y con ese sabor natural que lleva años siendo un clásico.",
    "desc_short": "El caramelo de toda la vida, relleno de miel. Suave, reconfortante y con ese sabor natural que lleva años siendo un clásico.",
    "descripcion": "Los caramelos rellenos de miel de Gerio son de esos dulces que te recuerdan a casa. Tienen esa dulzura cálida y reconfortante que solo aporta la miel, con un exterior de caramelo clásico y un relleno jugoso que te sorprende cada vez. Perfectos para el momento de relax del sofá, para calmar ese antojo dulce a media tarde o simplemente porque un buen caramelo de miel nunca está de más. Gerio lleva décadas haciéndolos igual de bien. Bolsa de 1 kg.",
    "descripcion_html": "<div>\n<p>Los caramelos rellenos de miel de Gerio son de esos dulces que te recuerdan a casa. Tienen esa dulzura cálida y reconfortante que solo aporta la miel, con un exterior de caramelo clásico y un relleno jugoso que te sorprende cada vez.</p>\n<p>Perfectos para el momento de relax del sofá, para calmar ese antojo dulce a media tarde o simplemente porque un buen caramelo de miel nunca está de más. Gerio lleva décadas haciéndolos igual de bien.</p>\n<p>Bolsa de 1 kg.</p>\n</div>",
    "referencia": "2651",
    "marca": "Gerio",
    "features": [],
    "url_proveedor": "https://www.lekkerlandstore.com/caramelos/1925-caramelo-relleno-de-miel-1-kg-gerio.html",
    "en_stock": true
  },
  {
    "id": 14,
    "nombre": "Taco Lápiz Nata Fresa 1 kg King Regal",
    "cat": "regaliz",
    "cat_label": "Regaliz",
    "art": "licorice",
    "slug": "taco-lapiz-nata-fresa-1-kg-king-regal",
    "img": "images/productos/taco-lapiz-nata-fresa-1-kg-king-regal.jpg",
    "img_zoom": "https://www.lekkerlandstore.com/140744-large_default/taco-lapiz-nata-fresa-1-kg-king-regal.jpg",
    "price": 6.19,
    "precio_proveedor": 4.41,
    "precio_comp": 6.75,
    "meta": "Regaliz blanco relleno de crema de fresa. La chuche blanda y cremosa que no puedes dejar de comer una vez que empiezas.",
    "desc_short": "Regaliz blanco relleno de crema de fresa. La chuche blanda y cremosa que no puedes dejar de comer una vez que empiezas.",
    "descripcion": "Los Tacos Lápiz Nata Fresa de King Regal son la chuche perfecta para los que prefieren lo dulce sobre lo intenso. Regaliz blanco y suavísimo, relleno de crema con sabor a fresa. Cada trozo se deshace solo en la boca dejando un rastro dulce que pide más. Son tiernos, cremosos y con un sabor a fresa equilibrado que no empalaga. Perfectos para picar mientras ves algo, compartir con los amigos o meter en cualquier bol de chuches y ver cómo desaparecen en minutos. Bolsa de 1 kg.",
    "descripcion_html": "<div>\n<p>Los Tacos Lápiz Nata Fresa de King Regal son la chuche perfecta para los que prefieren lo dulce sobre lo intenso. Regaliz blanco y suavísimo, relleno de crema con sabor a fresa. Cada trozo se deshace solo en la boca dejando un rastro dulce que pide más.</p>\n<p>Son tiernos, cremosos y con un sabor a fresa equilibrado que no empalaga. Perfectos para picar mientras ves algo, compartir con los amigos o meter en cualquier bol de chuches y ver cómo desaparecen en minutos.</p>\n<p>Bolsa de 1 kg.</p>\n</div>",
    "referencia": "4507",
    "marca": "Marca:",
    "features": [],
    "url_proveedor": "https://www.lekkerlandstore.com/regalices/3846-taco-lapiz-nata-fresa-1-kg-king-regal.html",
    "en_stock": true
  },
  {
    "id": 15,
    "nombre": "Sobres Soda Dinos Lima Limón (40 ud) Cerdán",
    "cat": "caramelos",
    "cat_label": "Caramelos",
    "art": "wrapped",
    "slug": "sobres-soda-dinos-lima-limon-40-ud-cerdan",
    "img": "images/productos/sobres-soda-dinos-lima-limon-40-ud-cerdan.jpg",
    "img_zoom": "https://www.lekkerlandstore.com/140684-large_default/sobres-soda-dinos-lima-limon-40-ud-cerdan.jpg",
    "price": 9.79,
    "precio_proveedor": 7.0,
    "precio_comp": 10.55,
    "meta": "Piruleta de lima-limón + polvo ácido efervescente + dinosaurio en el sobre. Todo lo que necesitas para un pica-pica de nivel.",
    "desc_short": "Piruleta de lima-limón + polvo ácido efervescente + dinosaurio en el sobre. Todo lo que necesitas para un pica-pica de nivel.",
    "descripcion": "Los Sobres Soda Dinos de Lima Limón son la chuche para los amantes del ácido. Abres el sobre con su dinosaurio de colores, sacas la piruleta de lima-limón, la mojas en el polvo efervescente... y el efecto ácido-cítrico te arrasa la lengua de la mejor manera posible. Esa explosión de lima-limón refrescante junto con el pica-pica del polvo es una combinación ganadora. El sabor es intenso, cítrico y muy fresco — el tipo de chuche que consigue que no puedas parar hasta el último sobre. Caja de 40 sobres individuales.",
    "descripcion_html": "<div>\n<p>Los Sobres Soda Dinos de Lima Limón son la chuche para los amantes del ácido. Abres el sobre con su dinosaurio de colores, sacas la piruleta de lima-limón, la mojas en el polvo efervescente... y el efecto ácido-cítrico te arrasa la lengua de la mejor manera posible.</p>\n<p>Esa explosión de lima-limón refrescante junto con el pica-pica del polvo es una combinación ganadora. El sabor es intenso, cítrico y muy fresco — el tipo de chuche que consigue que no puedas parar hasta el último sobre.</p>\n<p>Caja de 40 sobres individuales.</p>\n</div>",
    "referencia": "15062",
    "marca": "Cerdán",
    "features": [],
    "url_proveedor": "https://www.lekkerlandstore.com/piruletas/3816-sobres-soda-dinos-lima-limon-40-ud-cerdan.html",
    "en_stock": true
  },
  {
    "id": 16,
    "nombre": "Lagrimas de eucalipto 1 kg Damel",
    "cat": "gominolas",
    "cat_label": "Gominolas",
    "art": "bear",
    "slug": "lagrimas-de-eucalipto-1-kg-damel",
    "img": "images/productos/lagrimas-de-eucalipto-1-kg-damel.jpg",
    "img_zoom": "https://www.lekkerlandstore.com/141093-large_default/lagrimas-de-eucalipto-1-kg-damel.jpg",
    "price": 5.99,
    "precio_proveedor": 4.35,
    "precio_comp": 6.55,
    "meta": "Gomitas con forma de lágrima y sabor a eucalipto que combinan lo dulce con lo refrescante. La chuche mentolada que te refresca por dentro.",
    "desc_short": "Gomitas con forma de lágrima y sabor a eucalipto que combinan lo dulce con lo refrescante. La chuche mentolada que te refresca por dentro.",
    "descripcion": "Las Lágrimas de Eucalipto de Damel son para los que quieren algo diferente. Gomita blanda y tierna con esa forma de gotita tan característica, y por dentro: eucalipto. Ese aroma fresco y mentolado que las convierte en algo único — ni caramelo normal ni chicle, sino algo propio. Son ideales para los momentos de relax, perfectas para compartir en reuniones y muy difíciles de dejar una vez que empiezas. Si te gustan las chuches con ese toque refrescante y aromático, estas son las tuyas. Bolsa de 1 kg.",
    "descripcion_html": "<div>\n<p>Las Lágrimas de Eucalipto de Damel son para los que quieren algo diferente. Gomita blanda y tierna con esa forma de gotita tan característica, y por dentro: eucalipto. Ese aroma fresco y mentolado que las convierte en algo único — ni caramelo normal ni chicle, sino algo propio.</p>\n<p>Son ideales para los momentos de relax, perfectas para compartir en reuniones y muy difíciles de dejar una vez que empiezas. Si te gustan las chuches con ese toque refrescante y aromático, estas son las tuyas.</p>\n<p>Bolsa de 1 kg.</p>\n</div>",
    "referencia": "15241",
    "marca": "Damel",
    "features": [],
    "url_proveedor": "https://www.lekkerlandstore.com/gominolas/4091-lagrimas-de-eucalipto-1-kg-damel.html",
    "en_stock": true
  },
  {
    "id": 17,
    "nombre": "Barrita Jungly 34 g (30 ud) Nestlé",
    "cat": "chocolate",
    "cat_label": "Chocolate",
    "art": "choc",
    "slug": "barrita-jungly-34-g-30-ud-nestle",
    "img": "images/productos/barrita-jungly-34-g-30-ud-nestle.jpg",
    "img_zoom": "https://www.lekkerlandstore.com/132457-large_default/snack-jungly-barrita-34-g-30-ud-nestle.jpg",
    "price": 18.49,
    "precio_proveedor": 13.5,
    "precio_comp": 19.9,
    "meta": "El chocolate con leche de la infancia, en su barrita de siempre. Jungly de Nestlé: cremoso, irresistible y capaz de alegrar cualquier momento.",
    "desc_short": "El chocolate con leche de la infancia, en su barrita de siempre. Jungly de Nestlé: cremoso, irresistible y capaz de alegrar cualquier momento.",
    "descripcion": "La barrita Jungly de Nestlé no necesita presentación. La conoces desde pequeño, tienes ese recuerdo especial de la primera vez que la comiste, y cuando la vuelves a probar es exactamente como la recordabas: chocolate con leche cremoso y suave con ese sabor tan característico que te transporta en un segundo. Es perfecta para cualquier momento del día — merienda, capricho a deshora o ese punto dulce que necesitas después de comer. Nestlé no falla, y Jungly es la prueba. Display de 30 barritas de 34 g.",
    "descripcion_html": "<div>\n<p>La barrita Jungly de Nestlé no necesita presentación. La conoces desde pequeño, tienes ese recuerdo especial de la primera vez que la comiste, y cuando la vuelves a probar es exactamente como la recordabas: chocolate con leche cremoso y suave con ese sabor tan característico que te transporta en un segundo.</p>\n<p>Es perfecta para cualquier momento del día — merienda, capricho a deshora o ese punto dulce que necesitas después de comer. Nestlé no falla, y Jungly es la prueba.</p>\n<p>Display de 30 barritas de 34 g.</p>\n</div>",
    "referencia": "9498",
    "marca": "Nestlé",
    "features": [],
    "url_proveedor": "https://www.lekkerlandstore.com/barritas-de-chocolate/3112-snack-jungly-barrita-34-g-30-ud-nestle.html",
    "en_stock": true
  },
  {
    "id": 18,
    "nombre": "Macedonia 250 ud Fini",
    "cat": "chicles",
    "cat_label": "Chicles",
    "art": "gum",
    "slug": "macedonia-250-ud-fini",
    "img": "images/productos/macedonia-250-ud-fini.jpg",
    "img_zoom": "https://www.lekkerlandstore.com/131058-large_default/macedonia-250-ud-fini.jpg",
    "price": 11.49,
    "precio_proveedor": 8.51,
    "precio_comp": 12.4,
    "meta": "La caja de chicles multicolor de Fini con sabores a fresa, manzana, limón, naranja y melón. Porque en la variedad está el gusto.",
    "desc_short": "La caja de chicles multicolor de Fini con sabores a fresa, manzana, limón, naranja y melón. Porque en la variedad está el gusto.",
    "descripcion": "La Macedonia de chicles de Fini es el paraíso de los que no se pueden decidir por un solo sabor. Fresa, manzana, limón, naranja, melón... cada chicle es una sorpresa diferente. Los de colores variados, sabores distintos, y todos buenos — así funciona la Macedonia. Son chicles de Fini, así que la textura y el sabor están garantizados. Perfectos para tener en el bolso e ir cogiendo según el humor del momento. El de fresa cuando quieres algo dulce, el de limón cuando necesitas algo más fresco... Caja de 250 unidades.",
    "descripcion_html": "<div>\n<p>La Macedonia de chicles de Fini es el paraíso de los que no se pueden decidir por un solo sabor. Fresa, manzana, limón, naranja, melón... cada chicle es una sorpresa diferente. Los de colores variados, sabores distintos, y todos buenos — así funciona la Macedonia.</p>\n<p>Son chicles de Fini, así que la textura y el sabor están garantizados. Perfectos para tener en el bolso e ir cogiendo según el humor del momento. El de fresa cuando quieres algo dulce, el de limón cuando necesitas algo más fresco...</p>\n<p>Caja de 250 unidades.</p>\n</div>",
    "referencia": "8044",
    "marca": "Fini",
    "features": [],
    "url_proveedor": "https://www.lekkerlandstore.com/chicles/1228-macedonia-250-ud-fini.html",
    "en_stock": true
  },
  {
    "id": 19,
    "nombre": "Mesa Dulce Azul",
    "cat": "conos",
    "cat_label": "Conos y cestas",
    "art": "cone",
    "slug": "mesa-dulce-azul",
    "img": "images/productos/mesa-dulce-azul.jpg",
    "img_zoom": "https://www.lekkerlandstore.com/140944-large_default/mesa-dulce-azul.jpg",
    "price": 51.09,
    "precio_proveedor": 37.95,
    "precio_comp": 55.0,
    "meta": "Una selección de chuches en tonos azules para una mesa dulce que impacta visualmente. Sabor a frambuesa y una pinta increíble.",
    "desc_short": "Una selección de chuches en tonos azules para una mesa dulce que impacta visualmente. Sabor a frambuesa y una pinta increíble.",
    "descripcion": "La Mesa Dulce Azul es para los que quieren que su celebración tenga un impacto visual que se recuerde. Todo en azul: las gominolas, los caramelos, las piruletas... coordinados de una forma que queda impresionante y además está delicioso. Contiene Lenguas Frambuesa de Fini, Torcidas Frambuesa de Fini, Finitronc Bicolor Azul de Fini, Bolas Azules de Bulgari y Lágrimas de Azúcar de Fini. Sabor a frambuesa dominante, dulce y muy fresco. Ideal para comuniones, cumpleaños temáticos, fiestas o cualquier ocasión en que quieras que la mesa de chuches sea la estrella del evento.",
    "descripcion_html": "<div>\n<p>La Mesa Dulce Azul es para los que quieren que su celebración tenga un impacto visual que se recuerde. Todo en azul: las gominolas, los caramelos, las piruletas... coordinados de una forma que queda impresionante y además está delicioso.</p>\n<p>Contiene Lenguas Frambuesa de Fini, Torcidas Frambuesa de Fini, Finitronc Bicolor Azul de Fini, Bolas Azules de Bulgari y Lágrimas de Azúcar de Fini. Sabor a frambuesa dominante, dulce y muy fresco.</p>\n<p>Ideal para comuniones, cumpleaños temáticos, fiestas o cualquier ocasión en que quieras que la mesa de chuches sea la estrella del evento.</p>\n</div>",
    "referencia": "15174",
    "marca": "Fini",
    "features": [],
    "url_proveedor": "https://www.lekkerlandstore.com/golosinas/3993-mesa-dulce-azul.html",
    "en_stock": true
  },
  {
    "id": 20,
    "nombre": "Aros fresa pica 1 kg Fini",
    "cat": "gominolas",
    "cat_label": "Gominolas",
    "art": "bear",
    "slug": "aros-fresa-pica-1-kg-fini",
    "img": "images/productos/aros-fresa-pica-1-kg-fini.jpg",
    "img_zoom": "https://www.lekkerlandstore.com/129829-large_default/aros-fresa-pica-1-kg-fini.jpg",
    "price": 5.39,
    "precio_proveedor": 4.08,
    "precio_comp": 5.9,
    "meta": "La gominola de fresa con toque pica de Fini. Suave por dentro, con azúcar pica por fuera, y con ese sabor a fresa que es pura adicción.",
    "desc_short": "La gominola de fresa con toque pica de Fini. Suave por dentro, con azúcar pica por fuera, y con ese sabor a fresa que es pura adicción.",
    "descripcion": "Los Aros Fresa Pica de Fini son de esas gominolas que todo el mundo tiene claras. Los ves en el bol, los pillas, te los comes, pillas otro. La textura es suave y blandita por dentro, con esa capita de azúcar que hace el toque pica por fuera, y el sabor a fresa es intenso y auténtico. Todo lo que necesitas de una gominola en una sola pieza. Sin gluten, sin huevo, sin frutos secos — para todos y en cualquier momento. Bolsa de 1 kg.",
    "descripcion_html": "<div>\n<p>Los Aros Fresa Pica de Fini son de esas gominolas que todo el mundo tiene claras. Los ves en el bol, los pillas, te los comes, pillas otro. La textura es suave y blandita por dentro, con esa capita de azúcar que hace el toque pica por fuera, y el sabor a fresa es intenso y auténtico.</p>\n<p>Todo lo que necesitas de una gominola en una sola pieza. Sin gluten, sin huevo, sin frutos secos — para todos y en cualquier momento.</p>\n<p>Bolsa de 1 kg.</p>\n</div>",
    "referencia": "2075",
    "marca": "Fini",
    "features": [],
    "url_proveedor": "https://www.lekkerlandstore.com/gominolas/386-aros-fresa-pica-1-kg-fini.html",
    "en_stock": true
  },
  {
    "id": 21,
    "nombre": "Burguer Gum 200 ud Fini",
    "cat": "chicles",
    "cat_label": "Chicles",
    "art": "gum",
    "slug": "burguer-gum-200-ud-fini",
    "img": "images/productos/burguer-gum-200-ud-fini.jpg",
    "img_zoom": "https://www.lekkerlandstore.com/136096-large_default/chicles-burguer-gum-200-ud-fini.jpg",
    "price": 12.59,
    "precio_proveedor": 9.46,
    "precio_comp": 13.64,
    "meta": "Un chicle con forma de hamburguesa mini que sabe mejor de lo que imaginas. El chicle más original de Fini para sorprender a cualquiera.",
    "desc_short": "Un chicle con forma de hamburguesa mini que sabe mejor de lo que imaginas. El chicle más original de Fini para sorprender a cualquiera.",
    "descripcion": "La Burguer Gum de Fini es la chuche más original que te vas a llevar hoy. Tiene forma de hamburguesa en miniatura — ese solo ya te gana. Pero luego la muerdes y resulta que está deliciosa, con ese sabor dulce y sorprendente que solo Fini consigue hacer tan bien. Es el tipo de chicle que se da entre amigos para ver su reacción, que se mete en las bolsas de cumpleaños para que haya algo diferente, o que simplemente te comes porque sí, porque te apetece un chicle con personalidad. Caja de 200 unidades, cada una envuelta individualmente.",
    "descripcion_html": "<div>\n<p>La Burguer Gum de Fini es la chuche más original que te vas a llevar hoy. Tiene forma de hamburguesa en miniatura — ese solo ya te gana. Pero luego la muerdes y resulta que está deliciosa, con ese sabor dulce y sorprendente que solo Fini consigue hacer tan bien.</p>\n<p>Es el tipo de chicle que se da entre amigos para ver su reacción, que se mete en las bolsas de cumpleaños para que haya algo diferente, o que simplemente te comes porque sí, porque te apetece un chicle con personalidad.</p>\n<p>Caja de 200 unidades, cada una envuelta individualmente.</p>\n</div>",
    "referencia": "8021",
    "marca": "Fini",
    "features": [],
    "url_proveedor": "https://www.lekkerlandstore.com/chicles/1402-chicles-burguer-gum-200-ud-fini.html",
    "en_stock": true
  },
  {
    "id": 22,
    "nombre": "Snack Crunch 33 g (30 ud) Nestlé",
    "cat": "chocolate",
    "cat_label": "Chocolate",
    "art": "choc",
    "slug": "snack-crunch-33-g-30-ud-nestle",
    "img": "images/productos/snack-crunch-33-g-30-ud-nestle.jpg",
    "img_zoom": "https://www.lekkerlandstore.com/131397-large_default/chocolate-crujiente-con-avellana-nestle-snack.jpg",
    "price": 18.49,
    "precio_proveedor": 13.95,
    "precio_comp": 19.9,
    "meta": "Chocolate con leche Nestlé sobre capas de barquillo crujiente. El snack que combina lo mejor de los dos mundos en 33 gramos de pura felicidad.",
    "desc_short": "Chocolate con leche Nestlé sobre capas de barquillo crujiente. El snack que combina lo mejor de los dos mundos en 33 gramos de pura felicidad.",
    "descripcion": "El Snack Crunch de Nestlé es esa combinación que siempre gana: chocolate con leche cremoso por fuera, barquillo crujiente y ligero por dentro. Cada mordisco tiene ese contraste de texturas que hace que sea imposible comer solo uno. Es ligero, es crujiente, es chocolateado y es Nestlé — todas las garantías que necesitas. Perfecto para la merienda, para el camino al trabajo o para ese capricho dulce que te mereces después de un día largo. Display de 30 unidades de 33 g.",
    "descripcion_html": "<div>\n<p>El Snack Crunch de Nestlé es esa combinación que siempre gana: chocolate con leche cremoso por fuera, barquillo crujiente y ligero por dentro. Cada mordisco tiene ese contraste de texturas que hace que sea imposible comer solo uno.</p>\n<p>Es ligero, es crujiente, es chocolateado y es Nestlé — todas las garantías que necesitas. Perfecto para la merienda, para el camino al trabajo o para ese capricho dulce que te mereces después de un día largo.</p>\n<p>Display de 30 unidades de 33 g.</p>\n</div>",
    "referencia": "1317",
    "marca": "Nestlé",
    "features": [],
    "url_proveedor": "https://www.lekkerlandstore.com/chocolatinas/1003-chocolate-crujiente-con-avellana-nestle-snack.html",
    "en_stock": true
  }
];
